### ISSUE TITLE
How do we get details of the scores?

### ISSUE THREAD

**Issue by consultguru** [OfficeDev/O365-Cloud-Sec-Tooling#3]
Hi,

We have been trying to understand how to use the reporting API to check if we can enhance our internal solution by bringing in the securescore data.

We like the UX view in the securescore site. However we have our customers not wanting to go to a new site and rather check through our tool.

Couple of questions:
1.  How to get the details for the score?
     Say, calling the API we get the following. How do we list out the 10 admins? 
```
         {
                "referenceId": "AdminMFA",
                "score": 0,
                "maxScore": 50,
                "controlDetails": {
                    "count": "10",
                    "total": "10"
                }
            },
```
Checking the fiddler trace, we see that the UX calls for `GET /api/Remediation/GetAdminsWithOutMFA HTTP/1.1`. 

2.  Is it possible for us to request all of the details at once? Like pass a -details switch or something?

3.   OR provide us the preformed API to request the details, e.g.
```
         {
                "referenceId": "AdminMFA",
                "score": 0,
                "maxScore": 50,
                "controlDetails": {
                    "count": "10",
                    "total": "10"
                }
                "detailsURL": {
                    "url": "/api/Remediation/GetAdminsWithOutMFA",
                    "protocol": "HTTP",
                    "method": "GET"
                }
            },
```
4.  Provide us with 
- Action text: e.g. Enable MFA for all global admins
- List of threats: e.g. Threats:: Account Breach, Elevation of Privilege
- Action Category: Account

**Comment by bkoeller** [comment]
Hey Gururaj,
Thanks for reaching out. All of the control metadata is currently published as a CSV from the Score Analyzer page:
![image](https://user-images.githubusercontent.com/10888763/28139421-0dc401b0-6709-11e7-9792-c9330aa22313.png)
This list has all the metadata in the web client, and maps to the control score results vai the referenceID.
Thanks!
Brandon Koeller

**Comment by consultguru** [comment]
Thanks Brandon.
We now understand how to get the control list. 
Looking forward to getting the details , point #1 (How do we list out the 10 admins?)

**Comment by kulpravin** [comment]
We were able to get the control details through Graph API, however out of 59 actions we were able to pull the details only for 47 actions. Rest 12 actions are Not Scored and by default marked them as Incomplete. We understand that these actions are not scored, which means even if the corresponding actions are implemented, the secure score will not change. 
Is there any reason why these 12 actions are not being scored?
All actions are Data related so its important for us to get the details around those 12 actions. Is it possible for us to request details?

**Comment by bkoeller** [comment]
Hey! Thanks for the follow-up. The not scored items are ones that we have not sourced and published data for on the back end, but which are still valid security controls for the service. Rather than limit the set of controls to only those that we have telemetry for, we opted to publish everything and backfill as we acquire the data. No way to get them through the API now, but you can certainly go and source the telemetry from the service through other methods. For example, if you want the list of 10 global admins, you can call the azure ad graph call to get a list of all users in a specific group: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-graph-api-quickstart
Thanks!
BK

**Comment by consultguru** [comment]
@bkoeller , for many of the items, there's no direct graph API. e.g. getting MFA status for a user/admin is not currently available via graph API
case and point:  MFA for global admins, MFA for users

**Comment by sashank** [comment]
@kulpravin  i went through latest MS Graph API , but dont find any API to pull Secure Score Controls directy , [MS Graph API ](https://developer.microsoft.com/en-us/graph/docs/concepts/overview) , any reference greatly appreciated ?
